Introduce the start of automatic type checking (#710)
* Introduce the start of automatic type checking.

We're not running it as part of pre-commit yet so we don't get
error fatigue.

Signed-off-by: Kevin M Granger <kgranger@redhat.com>

* Fix node package name in github workflow

Signed-off-by: Kevin M Granger <kgranger@redhat.com>

* Update setup action versions for typecheck gh action; use caching

Signed-off-by: Kevin M Granger <kgranger@redhat.com>

* fix makefile for type checking, change apt to apt-get as per recommendation

Signed-off-by: Kevin M Granger <kgranger@redhat.com>

* Make type checking failure an error.

We're going to make the check itself not required for merging.

Signed-off-by: Kevin M Granger <kgranger@redhat.com>

* add warning to make target, mark gh action as not quite ready yet, and ignore error in gh action

Signed-off-by: Kevin M Granger <kgranger@redhat.com>

Signed-off-by: Kevin M Granger <kgranger@redhat.com>

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -18,6 +18,12 @@ if ! make -k lint; then
     failed=1
 fi
 
+# echo "📋 Type Checking, expect failures for now"
+# if ! make -k typecheck; then
+#     printf "\n\n"
+#     echo "Type checking failed, although this is to be expected for now." >&2
+# fi
+
 printf "\n\n"
 
 if [[ failed -ne 0 ]]; then
